###  Assignment No 4 ###

"""Assignment Title : Implement Bi-gram, Tri-gram word sequence and its count in text input
data using NLTK library"""


from nltk import ngrams
from nltk.util import ngrams

#unigram model
n = 1
sentence ="Our planet, Earth, is a remarkable world filled with natural wonders and endless variety. It spins gracefully around the Sun, providing the perfect conditions for life to exist. From the vast blue oceans that cover most of its surface to the lush green forests and expansive plains, Earth offers habitats for millions of living organisms. It is a place where nature, climate, and life interact in harmony, creating a dynamic and ever-changing environment."

unigrams = ngrams(sentence.split(), n)
print(f"\n***********   UNIGRAM    ************************")
for item in unigrams:
    print(item)
#bigram model
n = 2
sentence = "Our planet, Earth, is a remarkable world filled with natural wonders and endless variety. It spins gracefully around the Sun, providing the perfect conditions for life to exist. From the vast blue oceans that cover most of its surface to the lush green forests and expansive plains, Earth offers habitats for millions of living organisms. It is a place where nature, climate, and life interact in harmony, creating a dynamic and ever-changing environment."

unigrams = ngrams(sentence.split(), n)
print(f"\n***********   BIGRAM    ************************")
for item in unigrams:
    print(item)

#trigram model
n = 3
sentence = "Our planet, Earth, is a remarkable world filled with natural wonders and endless variety. It spins gracefully around the Sun, providing the perfect conditions for life to exist. From the vast blue oceans that cover most of its surface to the lush green forests and expansive plains, Earth offers habitats for millions of living organisms. It is a place where nature, climate, and life interact in harmony, creating a dynamic and ever-changing environment."
unigrams = ngrams(sentence.split(), n)
print(f"\n***********   TRIGRAM    ************************")
for item in unigrams:
    print(item)


'''
************    OUTPUT    ********************
***********   UNIGRAM    ************************
('Our',)
('planet,',)
('Earth,',)
('is',)
('a',)
('remarkable',)
('world',)
('filled',)
('with',)
('natural',)
('wonders',)
('and',)
('endless',)
('variety.',)
('It',)
('spins',)
('gracefully',)
('around',)
('the',)
('Sun,',)
('providing',)
('the',)
('perfect',)
('conditions',)
('for',)
('life',)
('to',)
('exist.',)
('From',)
('the',)
('vast',)
('blue',)
('oceans',)
('that',)
('cover',)
('most',)
('of',)
('its',)
('surface',)
('to',)
('the',)
('lush',)
('green',)
('forests',)
('and',)
('expansive',)
('plains,',)
('Earth',)
('offers',)
('habitats',)
('for',)
('millions',)
('of',)
('living',)
('organisms.',)
('It',)
('is',)
('a',)
('place',)
('where',)
('nature,',)
('climate,',)
('and',)
('life',)
('interact',)
('in',)
('harmony,',)
('creating',)
('a',)
('dynamic',)
('and',)
('ever-changing',)
('environment.',)

***********   BIGRAM    ************************
('Our', 'planet,')
('planet,', 'Earth,')
('Earth,', 'is')
('is', 'a')
('a', 'remarkable')
('remarkable', 'world')
('world', 'filled')
('filled', 'with')
('with', 'natural')
('natural', 'wonders')
('wonders', 'and')
('and', 'endless')
('endless', 'variety.')
('variety.', 'It')
('It', 'spins')
('spins', 'gracefully')
('gracefully', 'around')
('around', 'the')
('the', 'Sun,')
('Sun,', 'providing')
('providing', 'the')
('the', 'perfect')
('perfect', 'conditions')
('conditions', 'for')
('for', 'life')
('life', 'to')
('to', 'exist.')
('exist.', 'From')
('From', 'the')
('the', 'vast')
('vast', 'blue')
('blue', 'oceans')
('oceans', 'that')
('that', 'cover')
('cover', 'most')
('most', 'of')
('of', 'its')
('its', 'surface')
('surface', 'to')
('to', 'the')
('the', 'lush')
('lush', 'green')
('green', 'forests')
('forests', 'and')
('and', 'expansive')
('expansive', 'plains,')
('plains,', 'Earth')
('Earth', 'offers')
('offers', 'habitats')
('habitats', 'for')
('for', 'millions')
('millions', 'of')
('of', 'living')
('living', 'organisms.')
('organisms.', 'It')
('It', 'is')
('is', 'a')
('a', 'place')
('place', 'where')
('where', 'nature,')
('nature,', 'climate,')
('climate,', 'and')
('and', 'life')
('life', 'interact')
('interact', 'in')
('in', 'harmony,')
('harmony,', 'creating')
('creating', 'a')
('a', 'dynamic')
('dynamic', 'and')
('and', 'ever-changing')
('ever-changing', 'environment.')

***********   TRIGRAM    ************************
('Our', 'planet,', 'Earth,')
('planet,', 'Earth,', 'is')
('Earth,', 'is', 'a')
('is', 'a', 'remarkable')
('a', 'remarkable', 'world')
('remarkable', 'world', 'filled')
('world', 'filled', 'with')
('filled', 'with', 'natural')
('with', 'natural', 'wonders')
('natural', 'wonders', 'and')
('wonders', 'and', 'endless')
('and', 'endless', 'variety.')
('endless', 'variety.', 'It')
('variety.', 'It', 'spins')
('It', 'spins', 'gracefully')
('spins', 'gracefully', 'around')
('gracefully', 'around', 'the')
('around', 'the', 'Sun,')
('the', 'Sun,', 'providing')
('Sun,', 'providing', 'the')
('providing', 'the', 'perfect')
('the', 'perfect', 'conditions')
('perfect', 'conditions', 'for')
('conditions', 'for', 'life')
('for', 'life', 'to')
('life', 'to', 'exist.')
('to', 'exist.', 'From')
('exist.', 'From', 'the')
('From', 'the', 'vast')
('the', 'vast', 'blue')
('vast', 'blue', 'oceans')
('blue', 'oceans', 'that')
('oceans', 'that', 'cover')
('that', 'cover', 'most')
('cover', 'most', 'of')
('most', 'of', 'its')
('of', 'its', 'surface')
('its', 'surface', 'to')
('surface', 'to', 'the')
('to', 'the', 'lush')
('the', 'lush', 'green')
('lush', 'green', 'forests')
('green', 'forests', 'and')
('forests', 'and', 'expansive')
('and', 'expansive', 'plains,')
('expansive', 'plains,', 'Earth')
('plains,', 'Earth', 'offers')
('Earth', 'offers', 'habitats')
('offers', 'habitats', 'for')
('habitats', 'for', 'millions')
('for', 'millions', 'of')
('millions', 'of', 'living')
('of', 'living', 'organisms.')
('living', 'organisms.', 'It')
('organisms.', 'It', 'is')
('It', 'is', 'a')
('is', 'a', 'place')
('a', 'place', 'where')
('place', 'where', 'nature,')
('where', 'nature,', 'climate,')
('nature,', 'climate,', 'and')
('climate,', 'and', 'life')
('and', 'life', 'interact')
('life', 'interact', 'in')
('interact', 'in', 'harmony,')
('in', 'harmony,', 'creating')
('harmony,', 'creating', 'a')
('creating', 'a', 'dynamic')
('a', 'dynamic', 'and')
('dynamic', 'and', 'ever-changing')
('and', 'ever-changing', 'environment.')
'''
